### PR TITLE
Renumbering directories to match chapters

### PR DESCRIPTION
**Pull request by bhanafee**
Renumber directories to match chapter names. Update root build.sbt references.

### CODE REVIEW

**Review by ironfish — APPROVED** [review]

**Comment by ironfish** [comment]
@bhanafee looks like there are some conflicts to be resolved here as well.

**Comment by ironfish** [comment]
Reviewed the changes but there are some conflict.

--

Cheers,

Github: <Fe)))><
Twitter: <Fe)))><

/DKD

**Comment by bhanafee** [comment]
Can you elaborate on conflicts? It says "This branch has no conflicts with the base branch"

**Comment by ironfish** [comment]
@bhanafee your IDE should show you the merge conflicts. Did you rebase against master before committing?

**Comment by ironfish** [comment]
@bhanafee I will squash and merge instead.

**Pull request merged**
